<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PDINOTE-03" failures="3" tests="26" name="AllTests" time="271.007" errors="0" timestamp="2025-01-15T11:37:34 BRT">
  <testcase classname="base.LoginTest" name="testLogin" time="1.346"/>
  <testcase classname="ViewCare.ViewCareTest" name="testViewCare" time="6.095"/>
  <testcase classname="ViewCare.SalesPointTest" name="testOnlineEquipements" time="0.642"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFoundClientSalesPoint" time="0.232"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByClient" time="0.32"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByID" time="0.311"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByLastMessage" time="0.326"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByOnlineEquipment" time="0.322"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointBySalesPoint" time="0.326"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByServiceOrder" time="0.316"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByTotalEquipment" time="0.325"/>
  <testcase classname="ViewCare.SalesPointTest" name="testAssertNumberOfCLients" time="0.037">
    <failure type="java.lang.AssertionError" message="Number of Shown Sales Points And Number of Sales Points Are Different expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError: Number of Shown Sales Points And Number of Sales Points Are Different expected [3] but found [4]
at ViewCare.SalesPointTest.testAssertNumberOfCLients(SalesPointTest.java:155)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testAssertNumberOfCLients -->
  <testcase classname="ViewCare.SalesPointTest" name="testAssertNumberOfShowedResults" time="0.03"/>
  <testcase classname="ViewCare.EnterSalesPointTest" name="testFetchListAndClickTheTestSalesPoint" time="0.277"/>
  <testcase classname="ViewCare.EnterSalesPointTest" name="testValidateNameSalesPoint" time="0.064"/>
  <testcase classname="ViewCare.EnterSalesPointTest" name="testValidatesNumberOfOS" time="0.021">
    <failure type="java.lang.AssertionError" message="OS Number Does Not Match expected [2] but found [0]">
      <![CDATA[java.lang.AssertionError: OS Number Does Not Match expected [2] but found [0]
at ViewCare.EnterSalesPointTest.testValidatesNumberOfOS(EnterSalesPointTest.java:72)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testValidatesNumberOfOS -->
  <testcase classname="ViewCare.EnterControllerTest" name="testLastInfoFirstMonitorableIsValidController" time="0.565"/>
  <testcase classname="ViewCare.EnterControllerTest" name="testAcessEquipmentController" time="1.835"/>
  <testcase classname="ViewCare.ValidateControllerRemoteAccessTest" name="testTryRemoteAccess" time="46.661"/>
  <testcase classname="ViewCare.ValidateControllerRemoteAccessTest" name="testTogglePassword" time="1.553"/>
  <testcase classname="ViewCare.ValidateControllerRemoteAccessTest" name="testGenerateRandomPassword" time="4.63"/>
  <testcase classname="ViewCare.ValidateControllerInformationTest" name="testValidateNumberOfUsers" time="38.101"/>
  <testcase classname="ViewCare.ValidateControllerInformationTest" name="testValidateNumberOfBiometry" time="24.151"/>
  <testcase classname="ViewCare.ValidateControllerInformationTest" name="testValidateNumberOfTime" time="2.946"/>
  <testcase classname="ViewCare.ValidateControllerInformationTest" name="testValidateNumberOfAcess" time="99.608"/>
  <testcase classname="ViewCare.ValidateControllerInformationTest" name="testExportAccess" time="30.809">
    <failure type="java.lang.AssertionError" message="Test ExportAccess: Failed, download did not start expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test ExportAccess: Failed, download did not start expected [true] but found [false]
at ViewCare.ValidateControllerInformationTest.testExportAccess(ValidateControllerInformationTest.java:104)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testExportAccess -->
</testsuite> <!-- AllTests -->
