<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PDINOTE-03" failures="2" tests="20" name="AllTests" time="168.139" errors="0" timestamp="2025-01-20T11:25:48 BRT">
  <testcase classname="base.LoginTest" name="testLogin" time="0.765"/>
  <testcase classname="ViewCare.ViewCareTest" name="testViewCare" time="9.446"/>
  <testcase classname="ViewCare.SalesPointTest" name="testOnlineEquipements" time="0.637"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFoundClientSalesPoint" time="0.315"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByClient" time="0.35"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByID" time="0.336"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByLastMessage" time="0.317"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByOnlineEquipment" time="0.326"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointBySalesPoint" time="0.326"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByServiceOrder" time="0.323"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByTotalEquipment" time="0.329"/>
  <testcase classname="ViewCare.SalesPointTest" name="testAssertNumberOfCLients" time="0.039">
    <failure type="java.lang.AssertionError" message="Number of Shown Sales Points And Number of Sales Points Are Different expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError: Number of Shown Sales Points And Number of Sales Points Are Different expected [3] but found [4]
at ViewCare.SalesPointTest.testAssertNumberOfCLients(SalesPointTest.java:152)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testAssertNumberOfCLients -->
  <testcase classname="ViewCare.SalesPointTest" name="testAssertNumberOfShowedResults" time="0.03"/>
  <testcase classname="ViewCare.EnterSalesPointTest" name="testFetchListAndClickTheTestSalesPoint" time="0.271"/>
  <testcase classname="ViewCare.EnterSalesPointTest" name="testValidateNameSalesPoint" time="0.061"/>
  <testcase classname="ViewCare.EnterSalesPointTest" name="testValidatesNumberOfOS" time="0.018">
    <failure type="java.lang.AssertionError" message="OS Number Does Not Match expected [2] but found [0]">
      <![CDATA[java.lang.AssertionError: OS Number Does Not Match expected [2] but found [0]
at ViewCare.EnterSalesPointTest.testValidatesNumberOfOS(EnterSalesPointTest.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testValidatesNumberOfOS -->
  <testcase classname="ViewCare.EnterControllerTest" name="testLastInfoFirstMonitorableIsValidController" time="0.564"/>
  <testcase classname="ViewCare.EnterControllerTest" name="testAccessEquipmentController" time="1.863"/>
  <testcase classname="ViewCare.ControllerUserActionsTest" name="testCreateNewUser" time="100.208"/>
  <testcase classname="ViewCare.ControllerUserActionsTest" name="testDeleteUser" time="41.608"/>
</testsuite> <!-- AllTests -->
