<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PDINOTE-03" failures="2" tests="22" name="AllTests" time="237.22" errors="0" timestamp="2025-01-13T13:33:00 BRT">
  <testcase classname="base.LoginTest" name="testLogin" time="0.739"/>
  <testcase classname="ViewCare.ViewCareTest" name="testViewCare" time="10.229"/>
  <testcase classname="ViewCare.SalesPointTest" name="testOnlineEquipements" time="0.655"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFoundClientSalesPoint" time="0.221"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByClient" time="0.33"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByID" time="0.331"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByLastMessage" time="0.32"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByOnlineEquipment" time="0.328"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointBySalesPoint" time="0.322"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByServiceOrder" time="0.305"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByTotalEquipment" time="0.307"/>
  <testcase classname="ViewCare.SalesPointTest" name="testAssertNumberOfCLients" time="0.035">
    <failure type="java.lang.AssertionError" message="Number of Shown Sales Points And Number of Sales Points Are Different expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError: Number of Shown Sales Points And Number of Sales Points Are Different expected [3] but found [4]
at ViewCare.SalesPointTest.testAssertNumberOfCLients(SalesPointTest.java:178)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testAssertNumberOfCLients -->
  <testcase classname="ViewCare.SalesPointTest" name="testAssertNumberOfShowedResults" time="0.029"/>
  <testcase classname="ViewCare.EnterSalesPointTest" name="testFetchListAndClickTheTestSalesPoint" time="0.273"/>
  <testcase classname="ViewCare.EnterSalesPointTest" name="testValidateNameSalesPoint" time="0.057"/>
  <testcase classname="ViewCare.EnterSalesPointTest" name="testValidatesNumberOfOS" time="0.021">
    <failure type="java.lang.AssertionError" message="OS Number Does Not Match expected [2] but found [0]">
      <![CDATA[java.lang.AssertionError: OS Number Does Not Match expected [2] but found [0]
at ViewCare.EnterSalesPointTest.testValidatesNumberOfOS(EnterSalesPointTest.java:72)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testValidatesNumberOfOS -->
  <testcase classname="ViewCare.EnterControllerTest" name="testLastInfoFirstMonitorableIsValidController" time="0.566"/>
  <testcase classname="ViewCare.EnterControllerTest" name="testAcessEquipmentController" time="1.849"/>
  <testcase classname="ViewCare.ValidateControllerTest" name="validateNumberOfUsers" time="58.689"/>
  <testcase classname="ViewCare.ValidateControllerTest" name="validateNumberOfBiometry" time="28.358"/>
  <testcase classname="ViewCare.ValidateControllerTest" name="validateNumberOfTime" time="2.923"/>
  <testcase classname="ViewCare.ValidateControllerTest" name="validateNumberOfAcess" time="121.413"/>
</testsuite> <!-- AllTests -->
